z1_gazebo:
    # Publish all joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    # Use standard effort controllers for simulation
    Joint01_controller:
        type: effort_controllers/JointEffortController
        joint: joint1
        pid: {p: 1000.0, i: 0.0, d: 100.0}

    Joint02_controller:
        type: effort_controllers/JointEffortController
        joint: joint2
        pid: {p: 1000.0, i: 0.0, d: 100.0}

    Joint03_controller:
        type: effort_controllers/JointEffortController
        joint: joint3
        pid: {p: 1000.0, i: 0.0, d: 100.0}

    Joint04_controller:
        type: effort_controllers/JointEffortController
        joint: joint4
        pid: {p: 1000.0, i: 0.0, d: 100.0}

    Joint05_controller:
        type: effort_controllers/JointEffortController
        joint: joint5
        pid: {p: 1000.0, i: 0.0, d: 100.0}

    Joint06_controller:
        type: effort_controllers/JointEffortController
        joint: joint6
        pid: {p: 1000.0, i: 0.0, d: 100.0}

    Gripper_controller:
        type: effort_controllers/JointEffortController
        joint: jointGripper
        pid: {p: 500.0, i: 0.0, d: 50.0}